#!/usr/bin/env php
<?php

$testsDir = __DIR__ . '/../tests';

$position = $_SERVER['argc'] - 1;

if ($position === 0) {
	$_SERVER['argv'][++$position] = $testsDir;
}
$_SERVER['argv'][++$position] = '-c';

$os = stristr(PHP_OS, 'LINUX') ? 'unix' : 'win';
$_SERVER['argv'][++$position] = $testsDir . "/php-$os.ini";

// $_SERVER['argv'][++$position] = '--coverage';
// $_SERVER['argv'][++$position] = 'coverage.html';
// $_SERVER['argv'][++$position] = '--coverage-src';
// $_SERVER['argv'][++$position] = './../app';

$dir = $testsDir . '/_helpers/cache';

if (!is_dir($dir)) {
	mkdir($dir);
}

$rdi = new \RecursiveDirectoryIterator($dir, \RecursiveDirectoryIterator::SKIP_DOTS);
$rii = new \RecursiveIteratorIterator($rdi, \RecursiveIteratorIterator::CHILD_FIRST);
foreach ($rii as $entry) {
	if ($entry->isDir()) {
		rmdir($entry);
	} else {
		unlink($entry);
	}
}

require __DIR__ . '/../vendor/bin/tester';
