#!/usr/bin/env php
<?php

require __DIR__ . '/Runner.php';
require __DIR__ . '/Runner.php';
$runner = new \Testbench\Runner;

$vendorDir = $runner->findVendorDirectory();
$testsDir = dirname($vendorDir) . '/tests';

$script = array_shift($_SERVER['argv']);
$_SERVER['argv'] = $runner->prepareArguments($_SERVER['argv'], $testsDir);
array_unshift($_SERVER['argv'], $script);

echo "TESTBENCH edition\n";
require $vendorDir . '/nette/tester/src/tester.php';
